include: package:lint/analysis_options_package.yaml

analyzer:
  errors:
    todo: info

linter:
  rules:
    always_use_package_imports: false
    prefer_relative_imports: true
    always_specify_types: true
